title: "Yo, it's Joe"
description: "just your average Joe"
url: "https://jberusch.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
